//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ExchangeRatesSeries {
    
    private string tableField;
    
    private string currencyField;
    
    private string codeField;
    
    private ExchangeRatesSeriesRates ratesField;
    
    /// <remarks/>
    public string Table {
        get {
            return this.tableField;
        }
        set {
            this.tableField = value;
        }
    }
    
    /// <remarks/>
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public ExchangeRatesSeriesRates Rates {
        get {
            return this.ratesField;
        }
        set {
            this.ratesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ExchangeRatesSeriesRates {
    
    private ExchangeRatesSeriesRatesRate rateField;
    
    /// <remarks/>
    public ExchangeRatesSeriesRatesRate Rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ExchangeRatesSeriesRatesRate {
    
    private string noField;
    
    private System.DateTime effectiveDateField;
    
    private float midField;
    
    /// <remarks/>
    public string No {
        get {
            return this.noField;
        }
        set {
            this.noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime EffectiveDate {
        get {
            return this.effectiveDateField;
        }
        set {
            this.effectiveDateField = value;
        }
    }
    
    /// <remarks/>
    public float Mid {
        get {
            return this.midField;
        }
        set {
            this.midField = value;
        }
    }
}
